package com.example.ui.screens

object Translator {
    private val bnMap = mapOf(
        "app_title" to "ONTAR_Hisab (অন্তর হিসাব)",
        "app_subtitle" to "মুদির দোকানের হিসাব ও ক্যাশ রেজিস্টার",
        "login_title" to "ব্যবসা লগইন করুন",
        "login_email" to "ইমেইল অথবা মোবাইল নাম্বার",
        "register_email" to "ইমেইল অ্যাড্রেস",
        "login_pin" to "৪ সংখ্যার লগইন পিন",
        "register_pin" to "৪ সংখ্যার নতুন পিন কোড",
        "login_btn" to "লগইন করুন",
        "register_tab" to "নতুন রেজিস্টার",
        "login_tab" to "লগইন",
        "register_title" to "নতুন হিসাব খাতা খুলুন",
        "shop_name" to "দোকানের নাম (যেমন: মা ফুড মার্ট)",
        "phone_number" to "মোবাইল নাম্বার",
        "register_btn" to "নতুন অ্যাকাউন্ট খুলুন",
        "trial_btn" to "ডেমো কাস্টমার ও ট্রায়াল লগইন",
        "or_divider" to "অথবা সরাসরি প্রবেশ করুন",
        "dashboard_title" to "ড্যাশবোর্ড",
        "sales_summary" to "মোট বিক্রয়",
        "expense_summary" to "মোট খরচ",
        "profit_summary" to "নিট লাভ-লোকসান",
        "due_summary" to "বাকি আদায়যোগ্য",
        "owed_summary" to "ডিলার বকেয়া",
        "stock_manager" to "পণ্য স্টক খাতা",
        "sales_billing" to "দৈনিক বিক্রি",
        "customer_ledger" to "বাকি খাতা (গ্রাহক)",
        "dealer_ledger" to "ডিলার ও পাওনাদার",
        "reports" to "হিসাব নিকাশ ও রিপোর্ট",
        "ai_coach" to "এআই পরামর্শক (Premium)",
        "cloud_sync_ok" to "ক্লাউড ব্যাকআপ সচল",
        "add_item" to "নতুন পণ্য যুক্ত করুন",
        "item_name" to "পণ্যের নাম",
        "buy_price" to "ক্রয় মূল্য (৳)",
        "sell_price" to "বিক্রয় মূল্য (৳)",
        "quantity" to "স্টক পরিমাণ",
        "category" to "ক্যাটাগরি",
        "add_btn" to "যোগ করুন",
        "stock_inventory" to "স্টক ইনভেন্টরি",
        "out_of_stock" to "স্টক শেষ!",
        "low_stock" to "স্টক সীমিত",
        "in_stock" to "স্টক আছে",
        "actions" to "কার্যক্রম",
        "billing" to "টালি খাতা হিসাব",
        "select_item" to "পণ্য সিলেক্ট করুন",
        "select_customer" to "কাস্টমার সিলেক্ট করুন",
        "sell_quantity" to "বিক্রয়ের সংখ্যা/পরিমাণ",
        "cash_sale" to "নগদ বিক্রি (ক্যাশ)",
        "sell_now" to "টালি করুন & বিক্রি করুন",
        "add_customer" to "নতুন কাস্টমার যোগ করুন",
        "customer_name" to "কাস্টমারের নাম",
        "address" to "ঠিকানা/গ্রাম",
        "dues" to "বকেয়া",
        "record_payment" to "বাকি জমা আদায়",
        "amount_deposit" to "জমার পরিমাণ (৳)",
        "save_btn" to "সংরক্ষণ করুন",
        "add_custom_due" to "নতুন বাকি যোগ করুন",
        "due_amount" to "বাকির পরিমাণ (৳)",
        "reason" to "বাকির কারণ/নোট",
        "ai_sms_remind" to "এআই এসএমএস খসড়া",
        "copy_sms" to "কপি করুন",
        "add_dealer" to "নতুন ডিলার যোগ করুন",
        "company" to "কোম্পানি/সরবরাহকারী",
        "dealer_payout" to "ডিলার টাকা প্রদান/অগ্রিম জমা",
        "payout_amount" to "প্রদান বা অগ্রিম জমার পরিমাণ (৳)",
        "dealer_purchase" to "ডিলার ক্রয় রেকর্ড",
        "purchased_goods" to "কী কী মালামাল কিনলেন",
        "report_period" to "রিপোর্ট সময়কাল",
        "daily" to "দৈনিক",
        "weekly" to "সপ্তাহ",
        "monthly" to "মাসিক",
        "yearly" to "বার্ষিক",
        "net_health" to "ব্যবসার আর্থিক অবস্থা",
        "expense_btn" to "অন্যান্য খরচ লিখুন",
        "expense_title" to "খরচের খাত (যেমন: বিদ্যুৎ বিল)",
        "log_out" to "লগআউট",
        "premium_badge" to "প্রিমিয়াম সুবিধা",
        "ai_coach_desc" to "আপনার দোকান বিক্রি এবং খরচের হিসাব বিশ্লেষণ করে ফিনান্সিয়াল রিপোর্ট ও এআই ড্যাশবোর্ড আপডেট।" ,
        "owner_name" to "দোকানদারের পুরো নাম",
        "forget_pin" to "পিন ভুলে গেছেন?",
        "reset_pin_title" to "পিন উদ্ধার (ফরগেট পাসওয়ার্ড)",
        "enter_sim_otp" to "৪ সংখরের ওটিপি (সিমুলেশন: %s)",
        "verify_otp" to "ওটিপি ও পিন পরিবর্তন করুন",
        "new_pin_label" to "নতুন পিন কোড (৪ সংখ্যা)",
        "old_pin_label" to "বর্তমান পিন কোড",
        "confirm_pin_label" to "কমফার্ম নতুন পিন",
        "change_pin_btn" to "পিন পরিবর্তন করুন",
        "security_settings" to "পিন পরিবর্তন করুন (Settings)",
        "shop_pic" to "দোকানের ছবি (Image URL/URI)",
        "owner_pic" to "দোকানদারের প্রোফাইল ছবি (Image URL/URI)",
        "edit_profile_dialog" to "প্রোফাইল আপডেট করুন",
        "update_btn" to "আপডেট তথ্য",
        "preset_avatars" to "সুন্দর ডেমো ছবি নির্বাচন করুন",
        "shop_pic_placeholder" to "দোকান ছবি ১",
        "shop_pic_placeholder2" to "দোকান ছবি ২",
        "owner_pic_placeholder" to "মালিক ছবি ১",
        "owner_pic_placeholder2" to "মালিক ছবি ২"
    )

    private val enMap = mapOf(
        "app_title" to "ONTAR_Hisab (অন্তর হিসাব)",
        "app_subtitle" to "Grocery Manager & Premium Digital Ledger",
        "login_title" to "Business Log In",
        "login_email" to "Email or Phone Number",
        "register_email" to "Email Address",
        "login_pin" to "4-Digit Log In PIN",
        "register_pin" to "4-Digit Secure PIN",
        "login_btn" to "Sign In",
        "register_tab" to "New Register",
        "login_tab" to "Log In",
        "register_title" to "Open Business Account",
        "shop_name" to "Shop / Business name (e.g. Food Mart)",
        "phone_number" to "Mobile Number",
        "register_btn" to "Register My Business",
        "trial_btn" to "Demo Customers & Demo Database",
        "or_divider" to "Or Log In Directly As Trial",
        "dashboard_title" to "Dashboard",
        "sales_summary" to "Total Sales",
        "expense_summary" to "Expenses",
        "profit_summary" to "Net Income",
        "due_summary" to "Receivable Dues",
        "owed_summary" to "Dealer Owed Balance",
        "stock_manager" to "Stock Manager",
        "sales_billing" to "Billing & Sales",
        "customer_ledger" to "Customer Ledger",
        "dealer_ledger" to "Dealer Log",
        "reports" to "Tally Reports",
        "ai_coach" to "AI Business Advisor",
        "cloud_sync_ok" to "Cloud Sync Active",
        "add_item" to "Add Stock Item",
        "item_name" to "Item Name",
        "buy_price" to "Purchase Price (৳)",
        "sell_price" to "Sales Price (৳)",
        "quantity" to "Stock Quantity",
        "category" to "Category",
        "add_btn" to "Add",
        "stock_inventory" to "Stock Inventory",
        "out_of_stock" to "Out of stock!",
        "low_stock" to "Restock alert",
        "in_stock" to "Healthy stock",
        "actions" to "Actions",
        "billing" to "Sales Billing Entry",
        "select_item" to "Select Stock Item",
        "select_customer" to "Select Customer (Blank for Cash)",
        "sell_quantity" to "Quantity to Sell",
        "cash_sale" to "Cash Sale",
        "sell_now" to "Record Sale & Billing",
        "add_customer" to "Add Customer Account",
        "customer_name" to "Customer Name",
        "address" to "Address / Village",
        "dues" to "Balance Owed",
        "record_payment" to "Record Paid Amount",
        "amount_deposit" to "Amount Deposited (৳)",
        "save_btn" to "Save Changes",
        "add_custom_due" to "Add Custom Due",
        "due_amount" to "Due Amount (৳)",
        "reason" to "Note / Bill Details",
        "ai_sms_remind" to "Gemini SMS Reminder",
        "copy_sms" to "Copy Copywriter Text",
        "add_dealer" to "Register Dealer/Supplier",
        "company" to "Brand / Company / Supplier",
        "dealer_payout" to "Supplier Payment / Advance Deposit",
        "payout_amount" to "Payment / Advance Amount (৳)",
        "dealer_purchase" to "Record Dealer Purchase",
        "purchased_goods" to "Items purchased / Note",
        "report_period" to "Reporting Period",
        "daily" to "Daily",
        "weekly" to "Weekly",
        "monthly" to "Monthly",
        "yearly" to "Yearly",
        "net_health" to "Business Status Update",
        "expense_btn" to "Log Out-of-pocket Expense",
        "expense_title" to "Expense Reason (e.g. Electric bill)",
        "log_out" to "Log Out",
        "premium_badge" to "Premium Active",
        "ai_coach_desc" to "Analyses actual shop transactions, stocks and expenses to draft professional forecasts and strategies easily.",
        "owner_name" to "Shop Owner Full Name",
        "forget_pin" to "Forgot PIN?",
        "reset_pin_title" to "Recover Secure PIN (Forgot PIN)",
        "enter_sim_otp" to "4-Digit OTP (Simulated: %s)",
        "verify_otp" to "Verify OTP & Update PIN",
        "new_pin_label" to "New PIN Code (4 Digits)",
        "old_pin_label" to "Current Security PIN",
        "confirm_pin_label" to "Confirm New PIN",
        "change_pin_btn" to "Update Password PIN",
        "security_settings" to "Change Safety PIN (Settings)",
        "shop_pic" to "Shop Image (URL/URI)",
        "owner_pic" to "Owner Profile Pic (URL/URI)",
        "edit_profile_dialog" to "Update Profile Details",
        "update_btn" to "Update Profile",
        "preset_avatars" to "Select Beautiful Shop/Owner Visuals",
        "shop_pic_placeholder" to "Shop Pic 1",
        "shop_pic_placeholder2" to "Shop Pic 2",
        "owner_pic_placeholder" to "Owner Pic 1",
        "owner_pic_placeholder2" to "Owner Pic 2"
    )

    fun get(key: String, isBengali: Boolean): String {
        return if (isBengali) {
            bnMap[key] ?: key
        } else {
            enMap[key] ?: key
        }
    }
}
